#!/bin/sh

[ ! -n "${mg_home}" ] && . mg
need_mg_dir

### Run a command for each child repository

for child in $children; do
  if [ ! -e $child ]; then
    echo_fail $child "does not exist, run mg update"
  elif [ ! -d $child ]; then
    echo_fail $child "exists and is not a directory, skipping!"
  else
    if [ ! -d $child/.git ]; then
      echo_fail $child "exists and is not a git repository, skipping!"
    else
      mg_exec $child $@
    fi
  fi
done
